// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.Flames.Infrastructure")]
[assembly: AssemblyProductAttribute("Plainion.Flames")]
[assembly: AssemblyDescriptionAttribute("Plainion.Flames")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("2.0")]
[assembly: AssemblyFileVersionAttribute("2.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.Flames.Infrastructure";
        internal const System.String AssemblyProduct = "Plainion.Flames";
        internal const System.String AssemblyDescription = "Plainion.Flames";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "2.0";
        internal const System.String AssemblyFileVersion = "2.0";
    }
}
