// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.Flames.Viewer")]
[assembly: AssemblyProductAttribute("Plainion.Flames")]
[assembly: AssemblyDescriptionAttribute("Plainion.Flames")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.Flames.Viewer";
        internal const System.String AssemblyProduct = "Plainion.Flames";
        internal const System.String AssemblyDescription = "Plainion.Flames";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "1.0";
        internal const System.String AssemblyFileVersion = "1.0";
    }
}
